name: Build Demo

on:
  push:
    branches: [main]
    paths:
      - 'demo/**'
  pull_request:
    paths:
      - 'demo/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: demo/package-lock.json

      - name: Install dependencies
        working-directory: ./demo
        run: npm ci

      - name: Build demo
        working-directory: ./demo
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: demo-dist
          path: demo/dist/
          retention-days: 7
